### ISSUE TITLE
手动切换输入语言（使用Alt+Shift）后光标颜色没有改变

### ISSUE THREAD

**Issue by szw0407** [beishanyufu/ime-and-cursor#11]
由于一些原因，本人把此插件绑定的快捷键删除了，使用系统的Alt+Shift切换语言。

但是此时，会发现此插件的光标颜色不会随之改变。也许作者默认了大家打开文件后不会手动切换语言？

当然了，这个插件配合 Smart IME 使用体验确实很好，很少需要真的手动切换输入法~

**Comment by beishanyufu** [comment]
受 vscode 所提供的 api 所限，插件无法监听到 shift、alt + shift 这样的按键事件，所以如果不使用 vscode 设置的快捷键切换语言，就会发生光标颜色和输入语言不对应的情况。

**Comment by szw0407** [comment]
能否考虑一下，比如给每次改变光标位置的时候，或者每隔一段时间（比如200ms）获取一下当前的输入法状态？
当前这个插件似乎，一旦不再与系统同步语言后，不论如何都不会更新颜色状态了——除非重新启动编辑器。

**Comment by beishanyufu** [comment]
可以，我先试试。另外，还是建议你在 vscode 里给输入法切换设个快捷键，如果默认的 shift + space 不方便用，可以换个别的。

**Comment by beishanyufu** [comment]
发布了一个新版本，可在 vscode 中更新。
新版添加了你建议的持续获取输入法功能。默认处于未开启状态，可在设置中填写间隔时间来开启。不过，间隔时间太短的话可能会比较耗电，具体情况会因电脑环境而不同，可以开启后观察一下。

**Comment by szw0407** [comment]
感谢~
