### ISSUE TITLE
 搭配vim使用时并不能在进入normal模式下自动切换为英文输入法, 反而切换为中文输入法, 应该是判断当前所属的输入法状态弄反了.

### ISSUE THREAD

**Issue by forFamilyGitHub** [beishanyufu/ime-and-cursor#12]
我照着作者的说明在vscode的配置文件settings.json文件添加了这一行之后, 
    // 如需本插件帮忙在 Vim 进入 Normal 模式时将输入语言自动切换为英文，那就再多加一项设置：
    "ime-and-cursor.helpVim": true,      // 不能在中文输入状态下按Escape键自动切换为英文输入法, 相反, 在英文输入状态下按Escape键居然自动切换为中文输入法. 

在vim 的 Insert 模式下输入, 不能在中文输入状态下按Escape键自动切换为英文输入法, 相反, 在英文输入状态下按Escape键居然自动切换为中文输入法. 

所以, 我觉得作者在判断当前输入法状态时判断错了, 把中英文输入法状态搞反了. 
希望作者百忙中抽空解决下这个bug. 感激不尽

**Comment by beishanyufu** [comment]
我这里使用是正常的。你可以看一下，这三项是不是做了如下设置：

"ime-and-cursor.cursorStyle.enable": false,
"ime-and-cursor.cursorColor.enable": true,
"ime-and-cursor.useWithVim": true,

另外，此插件是根据光标形状来判断何时辅助切换输入法的，所以需要 vim 保持默认光标形状设置（默认 insert 模式使用竖线型光标，nomal 模式使用块状光标）。

**Comment by forFamilyGitHub** [comment]
现在解决了. 感激不尽. 祝大佬工作顺利，事业蒸蒸日上, 身体健康, 阖家辛福.
"ime-and-cursor.cursorStyle.enable": false, 
我复制粘贴这一行时复制错了, 本来大佬指明的是正确的, 该值为false, 不知道为何我的变成true了.

**Comment by beishanyufu** [comment]
解决了就好！感谢支持！祝万事如意，幸福安康！！
