### ISSUE TITLE
搜狗输入法经常只能输入英文

### ISSUE THREAD

**Issue by kaich** [beishanyufu/ime-and-cursor#13]
Mac系统，中文设置的是搜狗， 英文设置的是Abc，用的vim插件，经常切换到搜狗输入法无法输入中文，输入的还是英文，而且光标的颜色也没有变化.

**Comment by beishanyufu** [comment]
是否已按照说明安装了输入法切换工具 im-select ,并完成了本插件的相关设置？
手头没有Mac，希望能有路过的Mac用户帮忙看看~

**Comment by kaich** [comment]
@beishanyufu 是的，已经安装 im-select， 并填入相应的key了。
添加了相应的vim相关配置，并且也添加了 `"ime-and-cursor.helpVim": true`。

具体情况如下：

在结束vim的插入模式的时候，会自动切换成英文输入法。然后要输入中文的时候`Shift+Space`切换为搜狗输入法。 但是这样来回切换几次，搜狗就无法输入中文了。输入法切换快捷键`Shift+Space `也能正常使用。 

另外在搜狗输入法不能输入中文的时候，我切到浏览器的地址框里面，就可以正常输入中文。接着我再切回VScode，VScode里面就也可以正常输入中文了。

**Comment by beishanyufu** [comment]
不知道你说的搜狗无法输入中文是怎样一种情况。手上没Mac，不然我就装上vim插件和搜狗自己试一试了。给你几点提示，仅供参考（很可能没什么用）——
- 如果不使用 vim 插件，ime an cursor 配合搜狗能否正常工作？
- 使用vim插件，但换成别的中文输入法是否还会有无法输入中文的情况？

**Comment by kaich** [comment]
感谢回复，我已经发现问题所在了. `im-select` 在Mac上工作不正常。改用了[macism](https://github.com/laishulu/macism/)可以正常工作。我修改了一下ReadMe，是否需要提交”pull request"?

**Comment by beishanyufu** [comment]
能够把问题解决真是太好了。
另外，很需要对此插件在 mac 上的实际使用经验的分享，所以，欢迎提交！

**Comment by kaich** [comment]
已提交

**Comment by beishanyufu** [comment]
已合并。非常感谢！
