### ISSUE TITLE
使用反馈: 关于自动保存和参数覆盖

### ISSUE THREAD

**Issue by Hocnonsense** [beishanyufu/ime-and-cursor#16]
感谢作者提供的软件! 我今天早上从知乎看到了这个插件推荐, 就过来用了一下, 感觉非常有趣

目前一切顺利, 但使用这个插件时可能稍微改变一下使用习惯 (切换语言 ctrl+space 很难有效).

此外, 我还发现这个插件改变光标状态是通过修改配置文件完成的 (#4), 因此它会覆盖掉我原来的默认光标设置:
```yaml
        "editorCursor.background": "#2020ff",
        "editorCursor.foreground": "#DfDf00",
```
我认为这个行为是可能有破坏性的, 首先会覆盖原来的默认光标设置, 其次可能会引发不同窗口读写这个文件时的冲突

另一个可能与这个行为相关的问题, 也是我反馈的主要问题: 在未保存的文件里切换输入法时, 会造成当前文件的一次保存动作; 如果文件同时配置了自动格式化 (如 black/korofileheader) 等, 那么对未编辑完成的文件 (比如说尚未输入右括号, 或者缩进没调整好) 的格式化会造成编辑器错误修改换行, 提示错误等, 直接打断编辑时的思路...; 或者在打开还不希望修改的文件但未格式化的文件时, 才刚刚切换了输入法, 整个文件内容就全变了...

此外, 这个插件没有修改 "editorCursor.background", 但仍会删除这个设置, 不知道是有什么考量呢?

建议:
1. 不要在切换输入法的时候保存文件!!!
2. 在文档中说明对默认光标设置的覆盖行为, 提示用户提前保存原有光标设置
3. 不要删除 "editorCursor.background" 的设置
4. 允许用户调整默认作用域 (#4)

**Comment by beishanyufu** [comment]
首先，本插件并不会在切换输入法时去保存文件，你遇到的情况应该有别的原因（找到原因还请告知）。
切换输入法和光标的默认快捷键是 Shift+Space，也可以自行修改为别的组合键，比如 Ctrl+Space。
本插件可通过设置光标颜色和光标样式来反映输入法的变化。基于vscode extension api，设置光标样式可以在内存中实现，但设置光标颜色似乎只能通过配置文件。如果不希望修改配置文件可以考虑仅使用光标样式（在插件配置中设置一下即可）。
然后，你提到的
>此外, 这个插件没有修改 "editorCursor.background", 但仍会删除这个设置, 不知道是有什么考量呢?

我刚实验了一下，并不会删除这个设置（从源码也可以看出，只是通过api去更新 "editorCursor.foreground" 和 "terminalCursor.foreground"）。咋回事呢？

**Comment by Hocnonsense** [comment]
感谢提示! 我又尝试了一下, 切换输入法时保存文件的触发我似乎找到规律了, 但这是我刚刚的操作:
1. 修改配置文件
2. 打开一个文件进行编辑 (我是自动生成了一个 fileheader 并保存文件)
3. 编辑文件 (我输入了一系列空格, 模拟某些未完成的操作, 当保存时, 每行的尾随空格会被删除)
4. 切换输入法

https://github.com/beishanyufu/ime-and-cursor/assets/48747984/ecd6eaa7-f300-4e86-8f10-40fbec4c1d9d

可见, 输入法切换后, 当前打开的所有文件都自动运行了保存操作

另一个问题, 通过api去更新 "editorCursor.foreground" 和 "terminalCursor.foreground"）是没毛病的, 问题在于当我设置 "ime-and-cursor.cursorColor.enable" 为 false 的时候, "workbench.colorCustomizations" 的全部选项都被清空了...

https://github.com/beishanyufu/ime-and-cursor/assets/48747984/22be4e26-f254-43fb-a906-a7cce02baeef

感谢您的建议! 我不敢再开启 "ime-and-cursor.cursorColor.enable" 这个选项了

**Comment by beishanyufu** [comment]
你的vscode有没有配置成“每当保存一个文件时就自动对所有文件执行保存操作”？

**Comment by Hocnonsense** [comment]
没有看到这个选项欸, 最接近的可能是这两个:
![image](https://github.com/beishanyufu/ime-and-cursor/assets/48747984/937f2737-401f-4974-b732-e9086ac56a94)

**Comment by beishanyufu** [comment]
我也不知道是否有这样的功能。我只是想不出为什么你切换输入法就会自动保存文件。因为这个插件本身代码只涉及光标和输入法，并没有文件相关操作。唯一靠点边的就是设置光标颜色时api会去访问一下配置文件。你可以再看看不用光标颜色了切换输入法还不会自动保存文件。如果还会，可以再禁用一下别的插件试试看。

**Comment by beishanyufu** [comment]
我也不知道是否有这样的功能。我只是想不出为什么你切换输入法就会自动保存文件。因为这个插件本身代码只涉及光标和输入法，并没有文件相关操作。唯一靠点边的就是设置光标颜色时api会去访问一下配置文件。你可以再看看不用光标颜色了切换输入法还不会自动保存文件。如果还会，可以再禁用一下别的插件试试看。

**Comment by Hocnonsense** [comment]
感谢! 我也不知道为啥切换输入法就会自动保存, 而且一定是在我修改了设置选项之后再在编辑文件的时候切换输入法, 才会自动保存文件, 就像我录的视频里面一样; 如果我在之前没有调整设置选项, 估计就不会遇到这个问题.

我也尝试了, 只要禁止光标颜色跟随输入法, 就没有再遇到意外保存文件的事情了.

**Comment by beishanyufu** [comment]
不用谢。回头有时间我把取消使用光标颜色时会导致"workbench.colorCustomizations" 被清空的问题处理一下。
