### ISSUE TITLE
有没有办法设置ctrl+space切换中英文？

### ISSUE THREAD

**Issue by KZhang152** [beishanyufu/ime-and-cursor#5]
习惯使用ctrl+space切换中英文，有没有可能把快捷键改成ctrl+space？

**Comment by beishanyufu** [comment]
应该可以，shift+space本就是个普通的vscode快捷键。在vscode中打开键盘快捷键设置窗口（ctrl+k ctrl+s），搜索“切换输入法”，找到后设为你想用的快捷键就可以了。

**Comment by edwinhuish** [comment]
同求。

尝试过修改vscode的快捷键，但无效。

习惯使用中文输入法，用 ctrl + space 切换同一个中文输入法的中/英输入状态，而不是切换语言。

**Comment by Hocnonsense** [comment]
我试了一下, 添加第二个输入法是必须的, 但是 vscode 快捷键可以读取同一个中文输入法的中/英输入状态的切换键
当前切换键是 Ctrl+Shift+Space, 快捷键是可以用的:
![image](https://github.com/beishanyufu/ime-and-cursor/assets/48747984/52b0f056-4e51-4383-99d6-f51431981b2b)


但是当我把切换键设置为 Ctrl+Space 之后, 快捷键就失效了

系统: win11 专业版
