### ISSUE TITLE
意外的清空掉用户设置的 workbench.colorCustomizations

### ISSUE THREAD

**Issue by vitash** [beishanyufu/ime-and-cursor#9]
打开用户设置 Settings (JSON)  文件。本人设置了几个 workbench.colorCustomizations 选项，也使用 vim。按照介绍设置了4个插件的选项：
```
//"ime-and-cursor.cursorStyle.enable": false,
//"ime-and-cursor.cursorColor.enable": true,
"ime-and-cursor.useWithVim": true,
"ime-and-cursor.helpVim": true,
```
![image](https://github.com/beishanyufu/ime-and-cursor/assets/28255142/396b8c74-88be-4fe3-9072-d9b210cfffd3)
那两个注释掉的选项会在失去焦点时把 "workbench.colorCustomizations" 给设置成 {}，也就是清空掉所有选项了。

---
打扰了，查看 issue 后才发现和另一个重复了

**Comment by beishanyufu** [comment]
新版已修正
